name: move_base
description: MoveBase – KFZ-Fachbetriebe finden
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.5

  # Navigation
  go_router: ^14.0.0

  # Maps & Location
  google_maps_flutter: ^2.10.0
  geolocator: ^14.0.0
  geocoding: ^5.0.0

  # UI
  google_fonts: ^6.3.3
  cached_network_image: ^3.4.1

  # Utilities
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  intl: ^0.20.2
  provider: ^6.1.5
  http: ^1.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo1.png'
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
