// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSiNStdVj82iwVM_wo9boggY9P6HlLRxI',
    appId: '1:910436040491:web:0b1378b040c39459e6cf6e',
    messagingSenderId: '910436040491',
    projectId: 'unfallbericht-copy-uqwzlg',
    authDomain: 'unfallbericht-copy-uqwzlg.firebaseapp.com',
    storageBucket: 'unfallbericht-copy-uqwzlg.firebasestorage.app',
    measurementId: 'G-0YWFNQL5MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDas7YLt0_jCjPoD1vKOJfMP3wbvY_-ks',
    appId: '1:910436040491:android:7d56d9779517afcbe6cf6e',
    messagingSenderId: '910436040491',
    projectId: 'unfallbericht-copy-uqwzlg',
    storageBucket: 'unfallbericht-copy-uqwzlg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClAaL0n2RizfhnpEvfPqsSVgKOAj3r_Js',
    appId: '1:910436040491:ios:e625f40363e27eabe6cf6e',
    messagingSenderId: '910436040491',
    projectId: 'unfallbericht-copy-uqwzlg',
    storageBucket: 'unfallbericht-copy-uqwzlg.firebasestorage.app',
    iosBundleId: 'com.mycompany.moveBase',
  );
}
